version: '3.8'

services:
  bella-watcher:
    build: .
    container_name: bella-watcher
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/hostfs # Full access to host for backup and restore
      - ./backups:/app/backups # Store zip files here
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
